---
include:
  - board: nice_nano//zmk
    shield: dinkey34_left nice_view_adapter nice_view
  - board: nice_nano//zmk
    shield: dinkey34_right nice_view_adapter nice_view
  - board: nice_nano//zmk
    shield: dinkey34_left studio-rpc-usb-uart nice_view_adapter nice_view
