---
include:
  - board: nice_nano/nrf52840/zmk
    shield: dinkey34_left nice_view_adapter nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano/nrf52840/zmk
    shield: dinkey34_right nice_view_adapter nice_view_gem
  - board: nice_nano/nrf52840/zmk
    shield: settings_reset
